- name: Proxmox stuff
  hosts: proxmox
  vars:
    name: fedora
  tasks:
    - set_fact:
        yeppers: "fedora-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
    - proxmox_kvm:
        api_user    : root@pam
        api_password: dedsec
        api_host    : 192.168.1.20
        clone       : ansiblenode2   # The VM source
        name        : "{{ yeppers }}"  # The target VM name
        node        : proxmox
        storage     : local-zfs
        format      : qcow2
        timeout     : 500  # Note: The task can take a while. Adapt
    - name: start vm
      proxmox_kvm:
        api_user: root@pam
        api_password: dedsec
        api_host: 192.168.1.20
        name: "{{ yeppers }}"
        node: proxmox
        state: started
    - name: firststuff
      shell: qm list | grep "{{ yeppers }}" | awk '{ print $1 }'
      register: thevmid
    - name: debug
      debug:
        var: thevmid.stdout 
