---
- name: Create a Fedora 40 VM on Proxmox VE
  hosts: proxmox
  become: yes

  vars:
    proxmox_host: "192.168.1.20"
    username: root
    password: dedsec
    vmid: 101
    node_name: "fed-node-01"
    memory: 4096
    cores: 12
    disk_size: 30G
    template_name: "fedora-40-default_20240909_amd64.tar.xz"  # Ensure this template is uploaded to Proxmox VE
    os_type: l2m
    start_vm: yes

  tasks:
    - name: Ensure Proxmox PAM is enabled and configured for API access.
      proxmoxve_host_info:
        host: "{{ proxmox_host }}"
        username: "{{ username }}"
        password: "{{ password }}"

    - name: Create Fedora 40 VM
      proxmoxve_vm_config:
        host: "{{ proxmox_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vmid: "{{ vmid }}"
        node_name: "{{ node_name }}"
        memory: "{{ memory }}"
        cores: "{{ cores }}"
        disk_size: "{{ disk_size }}"
        template_name: "{{ template_name }}"
        os_type: "{{ os_type }}"

    - name: Start the VM if specified
      proxmoxve_vm_config:
        host: "{{ proxmox_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vmid: "{{ vmid }}"
        action: start
      when: start_vm | default(true)
